// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/access/{accessKey}/server-by-session/{sessionID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "使用访问密钥+SessionID 获取服务器详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问密钥",
                        "name": "accessKey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ServerInfo"
                        }
                    },
                    "401": {
                        "description": "无效的访问密钥",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "服务器不存在",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/access/{accessKey}/servers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "使用访问密钥获取服务器列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问密钥",
                        "name": "accessKey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ServerStatus"
                            }
                        }
                    },
                    "401": {
                        "description": "无效的访问密钥",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/access/{accessKey}/user-resources/{sessionID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "使用访问密钥获取用户资源数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问密钥",
                        "name": "accessKey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "SessionID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.UserResourceInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "无效的访问密钥",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "服务器不存在或没有数据",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/github/callback": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "GitHub OAuth 回调",
                "responses": {
                    "302": {
                        "description": "登录成功跳转",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "state 或 code 无效",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "GitHub 认证失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/github/login": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "GitHub OAuth 登录跳转",
                "responses": {
                    "302": {
                        "description": "跳转至 GitHub",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "未配置 GitHub OAuth",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登出",
                "responses": {
                    "204": {
                        "description": "退出成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取当前登录用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.AuthUser"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "数据库未初始化",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cache-stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "获取缓存统计信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "缓存未启用",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/data": {
            "post": {
                "description": "监控代理上报系统信息，支持双密钥校验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "上报监控数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目密钥（默认 public）",
                        "name": "X-Project-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "服务器密钥（RequireAuth=true 时需要）",
                        "name": "X-Server-Key",
                        "in": "header"
                    },
                    {
                        "description": "系统信息",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SystemInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "解析数据失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "无效的服务器密钥",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "数据保存失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deploy/agent-command": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deploy"
                ],
                "summary": "获取一键运行客户端的命令与示例.env",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据上报基址，默认 https://serverstatus.ltd",
                        "name": "base_url",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否开启用户资源采集，默认false",
                        "name": "user_resources",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/export/history": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "导出服务器历史数据为CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SessionID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目密钥",
                        "name": "project_key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最多返回条数，默认DataLimit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "回溯小时数，默认24",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "缺少session_id",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/export/servers": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "导出服务器列表为CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目密钥",
                        "name": "project_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "访问密钥（用于换取项目密钥）",
                        "name": "access_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/export/user-resources": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "导出指定服务器的用户资源为CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SessionID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目密钥",
                        "name": "project_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "缺少session_id",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/generate-access-key": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "生成访问密钥",
                "parameters": [
                    {
                        "description": "双密钥",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AccessKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.AccessKeyResponse"
                        }
                    },
                    "400": {
                        "description": "无效的请求格式",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "无效的服务器密钥或项目密钥",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/register-session": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "注册新的 Session",
                "parameters": [
                    {
                        "description": "主机与项目",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SessionRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SessionRegisterResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "项目密钥验证失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reload-config": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "配置热重载",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "重载失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/server/{sessionID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "获取指定服务器详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SessionID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ServerInfo"
                        }
                    },
                    "404": {
                        "description": "服务器不存在",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/servers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "获取服务器列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ServerStatus"
                            }
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "系统统计信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user-resources/{sessionID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_resources"
                ],
                "summary": "获取指定服务器的用户资源使用情况",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SessionID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.UserResourceInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "服务器不存在或没有数据",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/uuid-count": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "获取UUID数量统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "版本信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/visitor/aggregate": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "访客分组聚合",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page|referrer|domain|ua",
                        "name": "group_by",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目密钥",
                        "name": "project_key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最近小时数，默认24",
                        "name": "hours",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回条数，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.AggregatedVisitorItem"
                            }
                        }
                    },
                    "400": {
                        "description": "缺少 group_by",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "数据库未初始化",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/visitor/bindings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "列出域名绑定",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.DomainBinding"
                            }
                        }
                    },
                    "401": {
                        "description": "需要登录",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "数据库未初始化",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "新增或更新域名绑定",
                "parameters": [
                    {
                        "description": "域名绑定",
                        "name": "binding",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DomainBinding"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "需要登录",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "数据库未初始化",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/visitor/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "获取访客统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目密钥",
                        "name": "project_key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最近小时数，默认24",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "需要登录",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "数据库未初始化",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/visitor/track": {
            "get": {
                "produces": [
                    "image/gif"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "访客埋点上报",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页面URL",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "来源URL",
                        "name": "referrer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目密钥，空则自动推断或使用默认",
                        "name": "project_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/ws-stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "获取WebSocket连接统计信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "WebSocket未启用",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.AccessKeyRequest": {
            "type": "object",
            "properties": {
                "project_key": {
                    "type": "string"
                },
                "server_key": {
                    "type": "string"
                }
            }
        },
        "main.AccessKeyResponse": {
            "type": "object",
            "properties": {
                "access_key": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "project_key": {
                    "type": "string"
                }
            }
        },
        "main.AggregatedVisitorItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "main.AuthUser": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "config": {},
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.CPUInfo": {
            "type": "object",
            "properties": {
                "core_count": {
                    "type": "integer"
                },
                "model_name": {
                    "type": "string"
                },
                "usage_percent": {
                    "type": "number"
                }
            }
        },
        "main.DiskInfo": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "usage_percent": {
                    "type": "number"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "main.DomainBinding": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "project_key": {
                    "type": "string"
                }
            }
        },
        "main.GPUInfo": {
            "type": "object",
            "properties": {
                "memory_total": {
                    "type": "integer"
                },
                "memory_used": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "usage_percent": {
                    "type": "number"
                }
            }
        },
        "main.MemInfo": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "usage_percent": {
                    "type": "number"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "main.NetInfo": {
            "type": "object",
            "properties": {
                "bytes_recv": {
                    "description": "总接收字节数",
                    "type": "integer"
                },
                "bytes_sent": {
                    "description": "总发送字节数",
                    "type": "integer"
                },
                "interfaces": {
                    "description": "网卡详细信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.NetInterface"
                    }
                },
                "packets_recv": {
                    "description": "总接收包数",
                    "type": "integer"
                },
                "packets_sent": {
                    "description": "总发送包数",
                    "type": "integer"
                },
                "speed_recv": {
                    "description": "接收速率 (KB/s)",
                    "type": "number"
                },
                "speed_sent": {
                    "description": "发送速率 (KB/s)",
                    "type": "number"
                }
            }
        },
        "main.NetInterface": {
            "type": "object",
            "properties": {
                "addrs": {
                    "description": "IP地址列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bytes_recv": {
                    "description": "接收字节数",
                    "type": "integer"
                },
                "bytes_sent": {
                    "description": "发送字节数",
                    "type": "integer"
                },
                "is_up": {
                    "description": "网卡状态",
                    "type": "boolean"
                },
                "mtu": {
                    "description": "MTU",
                    "type": "integer"
                },
                "name": {
                    "description": "网卡名称",
                    "type": "string"
                },
                "packets_recv": {
                    "description": "接收包数",
                    "type": "integer"
                },
                "packets_sent": {
                    "description": "发送包数",
                    "type": "integer"
                },
                "speed_recv": {
                    "description": "接收速率 (KB/s)",
                    "type": "number"
                },
                "speed_sent": {
                    "description": "发送速率 (KB/s)",
                    "type": "number"
                }
            }
        },
        "main.OSInfo": {
            "type": "object",
            "properties": {
                "arch": {
                    "description": "兼容旧字段",
                    "type": "string"
                },
                "architecture": {
                    "description": "规范字段",
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "uptime": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "main.ProcessInfo": {
            "type": "object",
            "properties": {
                "cmdline": {
                    "type": "string"
                },
                "cpu_percent": {
                    "type": "number"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "memory_percent": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.ServerInfo": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.SystemInfo"
                    }
                },
                "last_seen": {
                    "type": "string"
                },
                "latest": {
                    "$ref": "#/definitions/main.SystemInfo"
                }
            }
        },
        "main.ServerStatus": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "type": "number"
                },
                "cpu_temp": {
                    "type": "number"
                },
                "disk_percent": {
                    "type": "number"
                },
                "gpu_temp": {
                    "description": "保持兼容性，主GPU温度",
                    "type": "number"
                },
                "gpus": {
                    "description": "所有GPU信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GPUInfo"
                    }
                },
                "hostname": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "max_temp": {
                    "type": "number"
                },
                "memory_percent": {
                    "type": "number"
                },
                "network_bytes_recv": {
                    "description": "总接收字节数",
                    "type": "integer"
                },
                "network_bytes_sent": {
                    "description": "总发送字节数",
                    "type": "integer"
                },
                "network_speed_recv": {
                    "description": "网络接收速率 (KB/s)",
                    "type": "number"
                },
                "network_speed_sent": {
                    "description": "网络发送速率 (KB/s)",
                    "type": "number"
                },
                "os": {
                    "type": "string"
                },
                "session_id": {
                    "description": "UUID session标识",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_resources": {
                    "description": "用户资源使用信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.UserResourceInfo"
                    }
                }
            }
        },
        "main.SessionRegisterRequest": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "project_key": {
                    "type": "string"
                }
            }
        },
        "main.SessionRegisterResponse": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "main.SystemInfo": {
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/main.CPUInfo"
                },
                "disk": {
                    "$ref": "#/definitions/main.DiskInfo"
                },
                "gpu": {
                    "description": "保持兼容性，主GPU信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/main.GPUInfo"
                        }
                    ]
                },
                "gpus": {
                    "description": "所有GPU信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GPUInfo"
                    }
                },
                "hostname": {
                    "type": "string"
                },
                "memory": {
                    "$ref": "#/definitions/main.MemInfo"
                },
                "network": {
                    "$ref": "#/definitions/main.NetInfo"
                },
                "os": {
                    "$ref": "#/definitions/main.OSInfo"
                },
                "project_key": {
                    "type": "string"
                },
                "session_id": {
                    "description": "UUID session标识",
                    "type": "string"
                },
                "temperature": {
                    "$ref": "#/definitions/main.TempInfo"
                },
                "timestamp": {
                    "type": "string"
                },
                "user_resources": {
                    "description": "用户资源使用信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.UserResourceInfo"
                    }
                }
            }
        },
        "main.TempInfo": {
            "type": "object",
            "properties": {
                "avg_temp": {
                    "type": "number"
                },
                "cpu_temp": {
                    "type": "number"
                },
                "gpu_temp": {
                    "type": "number"
                },
                "max_temp": {
                    "type": "number"
                },
                "sensors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            }
        },
        "main.UserResourceInfo": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "type": "number"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "memory_percent": {
                    "type": "number"
                },
                "process_count": {
                    "type": "integer"
                },
                "top_processes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.ProcessInfo"
                    }
                },
                "uid": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "ServerStatus API",
	Description:      "ServerStatus 监控 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
